### ISSUE TITLE
Other bot integration kills slackbot on message processing. 

### ISSUE THREAD

**Issue by plainenough** [plainenough/slackbot#49]
01-21 18:25 asyncio      ERROR    Task exception was never retrieved
future: <Task finished coro=<RTMClient._connect_and_read() done, defined at /usr/local/lib/python3.6/dist-packages/slack/rtm/client.py:307> exception=AttributeError("'Message' object has no attribute 'command'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slack/rtm/client.py", line 339, in _connect_and_read
    await self._read_messages()
  File "/usr/local/lib/python3.6/dist-packages/slack/rtm/client.py", line 390, in _read_messages
    await self._dispatch_event(event, data=payload)
  File "/usr/local/lib/python3.6/dist-packages/slack/rtm/client.py", line 440, in _dispatch_event
    self._execute_in_thread(callback, data)
  File "/usr/local/lib/python3.6/dist-packages/slack/rtm/client.py", line 465, in _execute_in_thread
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/slackbot/main.py", line 43, in catch_message
    message = Message(data, **kwargs)
  File "/opt/slackbot/message.py", line 42, in __init__
    self.run_command()
  File "/opt/slackbot/message.py", line 130, in run_command
    if self.command:
AttributeError: 'Message' object has no attribute 'command'
01-21 18:25 root         ERROR    A worker died. So should I. :(

**Comment by plainenough** [comment]
Fixed.
